# Generated by Django 6.0.8 on 2026-08-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_customrdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomrData',
            new_name='User',
        ),
    ]
